### ISSUE TITLE
Low scrolling performance on the page with feature photo.

### ISSUE THREAD

**Issue by kuoe0** [KuoE0/harmono#19]
The problem is caused by the following CSS code to make the feature photo as background:

``` css
#page-wrapper {
  background-attachment: fixed;
}
```

I found the low scrolling performance is more obvious on **Google Chrome** than **Mozilla Firefox**.
